### ISSUE TITLE
Selling with negative value

### ISSUE THREAD

**Issue by alxnegrila** [gcarq/freqtrade#140] opened 2017-11-24 08:31 UTC
BITTREX: Selling BTC/LTC (https://www.bittrex.com/Market/Index?MarketName=BTC-LTC) with limit 0.00889423 (profit: ~-0.81%)
But     "stoploss": -0.10

This issue happens on both develop and master

**Comment by gcarq** [comment] 2017-11-24 10:08
We introduced a basic sell_signal since the latest version. That causes the sell orders and is expected behaviour. There will be a configuration toggle for this in the future

**Comment by mrLittlepy** [comment] 2017-11-28 06:36
I have config file.  
"max_open_trades": 7,
    "stake_currency": "BTC",
    "stake_amount": 0.0008,
    "dry_run": false,
    "minimal_roi": {
        "50":  0.04,
        "40":  0.07,
        "30":  0.08,
        "0":  0.12
    },
    "stoploss": -50.40,
    "bid_strategy": {
        "ask_last_balance": 0.0

As of my understanding stop loss is in action only if currency losses about 5000% of its value. But bot time to time sells currency at 9% loss. Any ideas why?  


 but bot sometimes sell with negative profit. Any ideas why?
![sell_ord](https://user-images.githubusercontent.com/34053423/33305459-dc327048-d416-11e7-9503-9df907414dd7.png)

**Comment by jblestang** [comment] 2017-11-28 07:34
In some cases (extreme drop) the sell signals kicks in before the stoploss

**Comment by mrLittlepy** [comment] 2017-11-28 07:46
Is it possible to "disable", deactivate this signal?

**Comment by gcarq** [comment] 2017-11-28 15:43
This should be fixed with https://github.com/gcarq/freqtrade/commit/858d2329e57cf616e7a2e43e263da67099a6df20 on develop

**Comment by mrLittlepy** [comment] 2017-12-06 06:33
TNX nice

**Comment by pmaster555** [comment] 2017-12-06 09:15
I have a  "use_sell_signal": false
 but the bot is sell with negative profit. Any ideas why?

**Comment by glonlas** [comment] 2018-01-08 00:55
Is it still the case with all the improvement we have made on the bot this the last month?

**Comment by shusso** [comment] 2018-02-11 11:29
feel free to re-open if problem persists 👍

**Closed by shusso** 2018-02-11 11:29 UTC

**Comment by mutedstorm** [comment] 2018-07-10 04:36
I have set "use_sell_signal" to false and"sell_profit_only" to true but the Bot is still selling at a loss with the current version.
I have tried to set the stop loss to -1.5 but it keeps selling at a loss. How can i stop it from doing this?

**Comment by mutedstorm** [comment] 2018-07-10 13:39
I set the stop-loss only in the strategy, no stop-loss setting in the config.json.
I'll take a look at the Startup-log and open a new Issue.
