### ISSUE TITLE
error forcesell

### ISSUE THREAD

**Issue by pmaster555** [gcarq/freqtrade#248] opened 2017-12-28 12:25 UTC
Traceback (most recent call last):
  File "/home/super/bitterxbot/freqtrade/freqtrade/rpc/telegram.py", line 108, in wrapper
    return command_handler(*args, **kwargs)
  File "/home/super/bitterxbot/freqtrade/freqtrade/rpc/telegram.py", line 457, in _forcesell
    _exec_forcesell(trade)
  File "/home/super/bitterxbot/freqtrade/freqtrade/rpc/telegram.py", line 583, in _exec_forcesell
    execute_sell(trade, current_rate)
  File "/home/super/bitterxbot/freqtrade/freqtrade/main.py", line 131, in execute_sell
    _CONF['fiat_display_currency']
KeyError: 'fiat_display_currency'

in config 

  "max_open_trades": 27,
    "stake_currency": "BTC",
    "stake_amount": 0.003,
    "fiat_display_currency": "USD",
    "dry_run": false,

and other function work normaly

**Comment by pmaster555** [comment] 2017-12-28 17:01
this error with any sale, not only forcesell ...

**Comment by seansan** [comment] 2017-12-28 18:36
Same here #250

**Comment by glonlas** [comment] 2017-12-28 20:36
Interesting, I will have a look at it and add more unit tests to cover this case.

**Comment by eliashassing** [comment] 2017-12-29 10:42
same here

**Comment by gcarq** [comment] 2017-12-30 01:44
@glonlas I took a quick look over #239 and I think the issue is that we never require `fiat_display_currency` within conf jsonschema.

Possible solutions:
* make `fiat_display_currency` a required property in jsonschema
* default `fiat_display_currency` to `USD` if not present in config

**Comment by glonlas** [comment] 2017-12-30 01:49
@gcarq you are right the attribute is not mandatory in the jsonschema. I thought I did. First I will fix it. 

I also have this issue even by using this attribute in my config. I am investigating to see why the key does not exist.

**Comment by glonlas** [comment] 2017-12-30 01:55
I found it. This issue is due to the implementation of force_sell in telegram file.
https://github.com/gcarq/freqtrade/blob/develop/freqtrade/rpc/telegram.py#L581-L582

As you can see we are importing the function to use it later.

https://github.com/gcarq/freqtrade/blob/develop/freqtrade/main.py#L130-L131
But the config in execute_sell required main() to be loaded (to preload the config).

I will see how to redesign it. Otherwise it will finish in a dirty try/catch

**Comment by glonlas** [comment] 2017-12-31 01:45
This bug should be fixed in `develop` branch.

**Closed by glonlas** 2017-12-31 01:45 UTC
Labels: bug
