### ISSUE TITLE
Invalid ROI display

### ISSUE THREAD

**Issue by alxnegrila** [gcarq/freqtrade#141] opened 2017-11-24 08:33 UTC
ROI percentage is not displayed correctly when it has a value.

ROI: -0.00008624 (13.10%)

**Comment by gcarq** [comment] 2017-11-24 10:06
Can you give me the raw data `tradesv3.sqlite`, that I can reproduce it?

**Comment by cryptophunk** [comment] 2017-12-06 14:53
How is the ROI being calculated? I'm assuming it is based on the performance? Or based on performance + open trades?

**Comment by jblestang** [comment] 2017-12-06 16:18
Seems to be calculated using the stake amount. Using the number of currently opened trades would be also incorrect. 
You need to have the total stake amount (number of closed trades + number of open trades) and then

ROi = earned_amount / total_stake_amount

**Comment by glonlas** [comment] 2017-12-18 05:29
Hi,
I had the same issue, so I have fixed this issue with the PR: https://github.com/gcarq/freqtrade/pull/200

The issue come from /profit that uses the close_profit value that is sometimes wrong. 
Once the PR will be merged this issue will be fixed.

**Closed** 2017-12-22 19:15 UTC
Labels: bug
