### ISSUE TITLE
ERROR - Unable to create trade

### ISSUE THREAD

**Issue by hftcrypto** [gcarq/freqtrade#100] opened 2017-11-12 12:31 UTC
There's an issue with some of the market not being able to create a trade throwing below error.

2017-11-12 20:29:51,553 - __main__ - ERROR - Unable to create trade
Traceback (most recent call last):
  File "./freqtrade/main.py", line 40, in _process
    trade = create_trade(float(_CONF['stake_amount']))
  File "./freqtrade/main.py", line 184, in create_trade
    if get_buy_signal(_pair):
  File "/Users/arvin/dev/freqtrade/freqtrade/analyze.py", line 102, in get_buy_signal
    dataframe = analyze_ticker(pair)
  File "/Users/arvin/dev/freqtrade/freqtrade/analyze.py", line 85, in analyze_ticker
    dataframe = parse_ticker_dataframe(data)
  File "/Users/arvin/dev/freqtrade/freqtrade/analyze.py", line 25, in parse_ticker_dataframe
    .drop('BV', 1) \
  File "/Users/arvin/anaconda/envs/cryptobot/lib/python3.6/site-packages/pandas/core/generic.py", line 2161, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/arvin/anaconda/envs/cryptobot/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3624, in drop
    labels[mask])
ValueError: labels ['BV'] not contained in axis

**Comment by hftcrypto** [comment] 2017-11-12 12:48
These markets are throwing errors
"BTC_SYS",
"BTC_NEOS",
"BTC_BTS",

**Comment by vertti** [comment] 2017-11-13 17:44
I'm not able to reproduce that, all those markets return ticker info with BV column correctly.

**Comment by gcarq** [comment] 2017-11-13 17:47
Thanks a lot for creating this issue. This happend a few times in the last days. My assumption is that this occurs when a coin wallet is in maintenance mode or the rate limit has been hit.  #60 is also related to this.

I will create a workaround to fix this.

**Comment by gcarq** [comment] 2017-11-13 17:50
@vertti Me neither. It's a very weird behaviour, especially since they are marking the response as successful.

**Comment by hftcrypto** [comment] 2017-11-15 01:46
Thanks allot for fixing this. Issue can now be closed.

**Comment by gcarq** [comment] 2017-11-15 23:06
@hftcrypto you're welcome. BTW you can keep the issue open if an commit/PR is attached to it, it will be closed automatically once it's merged with master.

**Comment by gcarq** [comment] 2017-11-21 18:30
Should be fixed with 0.14.3, is this still an issue?

**Comment by hftcrypto** [comment] 2017-11-22 13:06
So far I have not encountered it anymore. Issue can now be closed.

**Closed** 2017-11-22 13:19 UTC
